/**
 * Crisis-path UI strings. English is canonical; the other seven languages
 * were generated once at development time via the live model (strict JSON
 * schema per language) and shipped as reviewed constants — deterministic at
 * runtime, no blank buttons possible (a unit test enforces full coverage).
 * Verified protocol content deliberately stays English; helpline numbers are
 * numerals everywhere.
 */
import type { LanguageCode } from "./languages";

/** Every localizable key on the crisis path. */
export const UI_KEYS = [
  "heroLead",
  "heroEmphasis",
  "heroTail",
  "modeIndividual",
  "modeCaregiver",
  "ctxKicker",
  "ctxAlone",
  "ctxWithSomeone",
  "setting_home",
  "setting_outside",
  "setting_work",
  "setting_social",
  "setting_driving",
  "speak",
  "listening",
  "liveVoice",
  "inputPlaceholder",
  "send",
  "emergencyHelp",
  "footerDisclaimer",
  "footerPrivacy",
  "cmd_urge_label",
  "cmd_urge_desc",
  "cmd_panic_label",
  "cmd_panic_desc",
  "cmd_close-to-using_label",
  "cmd_close-to-using_desc",
  "cmd_returned-to-use_label",
  "cmd_returned-to-use_desc",
  "cmd_need-someone_label",
  "cmd_need-someone_desc",
  "cmd_overdose-danger_label",
  "cmd_overdose-danger_desc",
  "cmd_possible-overdose_label",
  "cmd_possible-overdose_desc",
  "cmd_they-are-distressed_label",
  "cmd_they-are-distressed_desc",
  "cmd_start-conversation_label",
  "cmd_start-conversation_desc",
  "cmd_prepare-message_label",
  "cmd_prepare-message_desc",
  "cmd_caregiver-support_label",
  "cmd_caregiver-support_desc",
  "cmd_call-emergency_label",
  "cmd_call-emergency_desc"
] as const;

/** One localizable UI string identifier. */
export type UIKey = (typeof UI_KEYS)[number];

/** Full dictionary: every supported language covers every key. */
export const UI_STRINGS: Record<LanguageCode, Record<UIKey, string>> = {
  "en": {
    "heroLead": "What do you need ",
    "heroEmphasis": "right now",
    "heroTail": "?",
    "modeIndividual": "I need support",
    "modeCaregiver": "I'm supporting someone",
    "ctxKicker": "Right now",
    "ctxAlone": "I'm alone",
    "ctxWithSomeone": "With someone",
    "setting_home": "Home",
    "setting_outside": "Outside",
    "setting_work": "Work",
    "setting_social": "Social",
    "setting_driving": "Driving",
    "speak": "Speak",
    "listening": "Listening…",
    "liveVoice": "Live voice",
    "inputPlaceholder": "…or speak / type what's happening (optional)",
    "send": "Send",
    "emergencyHelp": "Emergency help",
    "footerDisclaimer": "IBUKI Circle complements professional and human care — it is not a diagnosis, treatment, or emergency service. In immediate danger, call",
    "footerPrivacy": "Privacy: what you tap, say, or type is used only to generate this response — never stored on our servers, never shared without your action.",
    "cmd_urge_label": "I'm having a strong urge",
    "cmd_urge_desc": "Get an immediate plan to ride it out",
    "cmd_panic_label": "I'm panicking or overwhelmed",
    "cmd_panic_desc": "Ground yourself with calm, small steps",
    "cmd_close-to-using_label": "I'm close to using",
    "cmd_close-to-using_desc": "One safe next action, right now",
    "cmd_returned-to-use_label": "I returned to use",
    "cmd_returned-to-use_desc": "No judgement — steady next steps",
    "cmd_need-someone_label": "I need someone now",
    "cmd_need-someone_desc": "Prepare a message to your circle",
    "cmd_overdose-danger_label": "Possible overdose / danger",
    "cmd_overdose-danger_desc": "Verified emergency help, immediately",
    "cmd_possible-overdose_label": "Possible overdose",
    "cmd_possible-overdose_desc": "Verified emergency steps, now",
    "cmd_they-are-distressed_label": "They're distressed or agitated",
    "cmd_they-are-distressed_desc": "Calm de-escalation wording",
    "cmd_start-conversation_label": "Help me start a conversation",
    "cmd_start-conversation_desc": "Supportive, non-blaming script",
    "cmd_prepare-message_label": "Prepare a supportive message",
    "cmd_prepare-message_desc": "Ready-to-send words of support",
    "cmd_caregiver-support_label": "I need support as a caregiver",
    "cmd_caregiver-support_desc": "Boundaries, self-care, and backup",
    "cmd_call-emergency_label": "Call emergency help",
    "cmd_call-emergency_desc": "112 and verified next steps"
  },
  "ta": {
    "heroLead": "உங்களுக்கு ",
    "heroEmphasis": "இப்போது",
    "heroTail": " என்ன தேவை?",
    "modeIndividual": "எனக்கு உதவி வேண்டும்",
    "modeCaregiver": "நான் ஒருவருக்கு உதவுகிறேன்",
    "ctxKicker": "இப்போது",
    "ctxAlone": "நான் தனியாக இருக்கிறேன்",
    "ctxWithSomeone": "யாரோ ஒருவருடன்",
    "setting_home": "வீடு",
    "setting_outside": "வெளியே",
    "setting_work": "வேலை",
    "setting_social": "மற்றவர்களுடன்",
    "setting_driving": "வாகனம் ஓட்டும்போது",
    "speak": "பேசுங்கள்",
    "listening": "கேட்கிறேன்…",
    "liveVoice": "நேரடி குரல்",
    "inputPlaceholder": "…அல்லது என்ன நடக்கிறது என்று பேசுங்கள் / தட்டச்சிடுங்கள் (விருப்பம்)",
    "send": "அனுப்பு",
    "emergencyHelp": "அவசர உதவி",
    "footerDisclaimer": "IBUKI Circle தொழில்முறை மற்றும் மனித ஆதரவுக்கு துணையாகும் — இது நோயறிதல், சிகிச்சை அல்லது அவசர சேவை அல்ல. உடனடி ஆபத்தில், 112-ஐ அழைக்கவும்",
    "footerPrivacy": "தனியுரிமை: நீங்கள் தட்டுவது, சொல்வது அல்லது தட்டச்சிடுவது இந்தப் பதிலை உருவாக்க மட்டுமே பயன்படுத்தப்படும் — எங்கள் சேவையகங்களில் சேமிக்கப்படாது; உங்கள் செயல் இல்லாமல் பகிரப்படாது.",
    "cmd_urge_label": "எனக்கு மிகுந்த தூண்டுதல் வருகிறது",
    "cmd_urge_desc": "அதை கடக்க உடனடி திட்டம் பெறுங்கள்",
    "cmd_panic_label": "எனக்கு பதட்டமாக அல்லது தாங்க முடியாமல் உள்ளது",
    "cmd_panic_desc": "அமைதியான, சிறிய படிகளால் நிலைநிறுத்திக் கொள்ளுங்கள்",
    "cmd_close-to-using_label": "நான் பயன்படுத்தப் போகும் நிலையில் இருக்கிறேன்",
    "cmd_close-to-using_desc": "இப்போதே ஒரு பாதுகாப்பான அடுத்த செயல்",
    "cmd_returned-to-use_label": "நான் மீண்டும் பயன்படுத்திவிட்டேன்",
    "cmd_returned-to-use_desc": "தீர்ப்பு இல்லை — உறுதியான அடுத்த படிகள்",
    "cmd_need-someone_label": "எனக்கு இப்போது யாராவது வேண்டும்",
    "cmd_need-someone_desc": "உங்கள் நெருக்கமானவர்களுக்கு ஒரு செய்தி தயாரிக்கவும்",
    "cmd_overdose-danger_label": "அதிக அளவு எடுத்திருக்கலாம் / ஆபத்து",
    "cmd_overdose-danger_desc": "உறுதிப்படுத்தப்பட்ட அவசர உதவி, உடனே",
    "cmd_possible-overdose_label": "அதிக அளவு எடுத்திருக்கலாம்",
    "cmd_possible-overdose_desc": "உறுதிப்படுத்தப்பட்ட அவசர படிகள், இப்போது",
    "cmd_they-are-distressed_label": "அவர்கள் பதற்றமாக அல்லது கலக்கமாக உள்ளனர்",
    "cmd_they-are-distressed_desc": "அமைதிப்படுத்த உதவும் வார்த்தைகள்",
    "cmd_start-conversation_label": "உரையாடலைத் தொடங்க உதவுங்கள்",
    "cmd_start-conversation_desc": "ஆதரவான, குற்றம் சாட்டாத உரை",
    "cmd_prepare-message_label": "ஆதரவான செய்தி தயாரிக்கவும்",
    "cmd_prepare-message_desc": "அனுப்பத் தயாரான ஆதரவு வார்த்தைகள்",
    "cmd_caregiver-support_label": "கவனிப்பவராக எனக்கு உதவி வேண்டும்",
    "cmd_caregiver-support_desc": "எல்லைகள், சுயகவனிப்பு, மற்றும் கூடுதல் உதவி",
    "cmd_call-emergency_label": "அவசர உதவியை அழைக்கவும்",
    "cmd_call-emergency_desc": "112 மற்றும் உறுதிப்படுத்தப்பட்ட அடுத்த படிகள்"
  },
  "hi": {
    "heroLead": "आपको ",
    "heroEmphasis": "अभी क्या चाहिए",
    "heroTail": "?",
    "modeIndividual": "मुझे सहारे की ज़रूरत है",
    "modeCaregiver": "मैं किसी का साथ दे रहा/रही हूँ",
    "ctxKicker": "अभी",
    "ctxAlone": "मैं अकेला/अकेली हूँ",
    "ctxWithSomeone": "किसी के साथ",
    "setting_home": "घर",
    "setting_outside": "बाहर",
    "setting_work": "काम पर",
    "setting_social": "लोगों के साथ",
    "setting_driving": "गाड़ी चला रहा/रही हूँ",
    "speak": "बोलें",
    "listening": "सुन रहे हैं…",
    "liveVoice": "लाइव आवाज़",
    "inputPlaceholder": "…या बताएं/लिखें क्या हो रहा है (वैकल्पिक)",
    "send": "भेजें",
    "emergencyHelp": "आपात मदद",
    "footerDisclaimer": "IBUKI Circle पेशेवर और मानवीय देखभाल का पूरक है — यह निदान, इलाज या आपात सेवा नहीं है। तुरंत खतरे में हों, तो कॉल करें",
    "footerPrivacy": "निजता: आप जो टैप, बोलते या लिखते हैं, उसका उपयोग सिर्फ यह जवाब बनाने के लिए होता है — हमारे सर्वर पर कभी सहेजा नहीं जाता, और आपकी कार्रवाई के बिना साझा नहीं किया जाता।",
    "cmd_urge_label": "मुझे बहुत तेज़ तलब हो रही है",
    "cmd_urge_desc": "इसे संभालने के लिए तुरंत योजना पाएं",
    "cmd_panic_label": "मुझे घबराहट या बहुत दबाव महसूस हो रहा है",
    "cmd_panic_desc": "शांत, छोटे कदमों से खुद को संभालें",
    "cmd_close-to-using_label": "मैं इस्तेमाल करने के करीब हूँ",
    "cmd_close-to-using_desc": "अभी एक सुरक्षित अगला कदम",
    "cmd_returned-to-use_label": "मैंने फिर से इस्तेमाल किया",
    "cmd_returned-to-use_desc": "कोई फैसला नहीं — बस अगले ठोस कदम",
    "cmd_need-someone_label": "मुझे अभी किसी की ज़रूरत है",
    "cmd_need-someone_desc": "अपने भरोसेमंद लोगों के लिए संदेश तैयार करें",
    "cmd_overdose-danger_label": "ओवरडोज़ या खतरे की आशंका",
    "cmd_overdose-danger_desc": "तुरंत सत्यापित आपात मदद",
    "cmd_possible-overdose_label": "ओवरडोज़ की आशंका",
    "cmd_possible-overdose_desc": "अभी सत्यापित आपात कदम",
    "cmd_they-are-distressed_label": "वे परेशान या बेचैन हैं",
    "cmd_they-are-distressed_desc": "शांत करने के लिए आसान शब्द",
    "cmd_start-conversation_label": "बात शुरू करने में मदद करें",
    "cmd_start-conversation_desc": "सहारा देने वाली, बिना दोष की बात",
    "cmd_prepare-message_label": "सहारे का संदेश तैयार करें",
    "cmd_prepare-message_desc": "भेजने के लिए तैयार सहारे के शब्द",
    "cmd_caregiver-support_label": "मुझे देखभालकर्ता के रूप में सहारा चाहिए",
    "cmd_caregiver-support_desc": "सीमाएं, अपनी देखभाल और सहारा",
    "cmd_call-emergency_label": "आपात मदद को कॉल करें",
    "cmd_call-emergency_desc": "112 और सत्यापित अगले कदम"
  },
  "bn": {
    "heroLead": "আপনার এখন কী দরকার ",
    "heroEmphasis": "এই মুহূর্তে",
    "heroTail": "?",
    "modeIndividual": "আমার সহায়তা দরকার",
    "modeCaregiver": "আমি কারও পাশে আছি",
    "ctxKicker": "এই মুহূর্তে",
    "ctxAlone": "আমি একা",
    "ctxWithSomeone": "কারও সঙ্গে",
    "setting_home": "বাড়ি",
    "setting_outside": "বাইরে",
    "setting_work": "কাজে",
    "setting_social": "সামাজিক পরিবেশে",
    "setting_driving": "গাড়ি চালাচ্ছি",
    "speak": "বলুন",
    "listening": "শুনছি…",
    "liveVoice": "সরাসরি কথা",
    "inputPlaceholder": "…অথবা কী হচ্ছে বলুন / লিখুন (ঐচ্ছিক)",
    "send": "পাঠান",
    "emergencyHelp": "জরুরি সহায়তা",
    "footerDisclaimer": "IBUKI Circle পেশাদার ও মানুষের যত্নের পরিপূরক — এটি রোগনির্ণয়, চিকিৎসা বা জরুরি সেবা নয়। তাৎক্ষণিক বিপদে কল করুন",
    "footerPrivacy": "গোপনীয়তা: আপনি যা ট্যাপ, বলেন বা লেখেন, তা শুধু এই উত্তর তৈরি করতে ব্যবহৃত হয় — আমাদের সার্ভারে কখনও রাখা হয় না, আপনার পদক্ষেপ ছাড়া কারও সঙ্গে ভাগ করা হয় না।",
    "cmd_urge_label": "খুব তীব্র তাগিদ হচ্ছে",
    "cmd_urge_desc": "এটা সামলানোর জন্য এখনই একটি পরিকল্পনা পান",
    "cmd_panic_label": "আমি আতঙ্কিত বা ভীষণ চাপে আছি",
    "cmd_panic_desc": "শান্ত ছোট ছোট ধাপে নিজেকে স্থির করুন",
    "cmd_close-to-using_label": "আমি ব্যবহার করার খুব কাছাকাছি",
    "cmd_close-to-using_desc": "এখনই একটি নিরাপদ পরের পদক্ষেপ",
    "cmd_returned-to-use_label": "আমি আবার ব্যবহার করেছি",
    "cmd_returned-to-use_desc": "কোনো বিচার নয় — স্থির পরের পদক্ষেপ",
    "cmd_need-someone_label": "এখনই আমার কাউকে দরকার",
    "cmd_need-someone_desc": "আপনার কাছের মানুষদের জন্য একটি বার্তা তৈরি করুন",
    "cmd_overdose-danger_label": "সম্ভাব্য ওভারডোজ / বিপদ",
    "cmd_overdose-danger_desc": "যাচাইকৃত জরুরি সহায়তা, এখনই",
    "cmd_possible-overdose_label": "সম্ভাব্য ওভারডোজ",
    "cmd_possible-overdose_desc": "যাচাইকৃত জরুরি পদক্ষেপ, এখনই",
    "cmd_they-are-distressed_label": "তিনি অস্থির বা খুব কষ্টে আছেন",
    "cmd_they-are-distressed_desc": "শান্ত করার সহজ কথা",
    "cmd_start-conversation_label": "কথা শুরু করতে সাহায্য করুন",
    "cmd_start-conversation_desc": "সহায়ক, দোষ না দেওয়া কথার নমুনা",
    "cmd_prepare-message_label": "একটি সহায়ক বার্তা তৈরি করুন",
    "cmd_prepare-message_desc": "পাঠানোর জন্য প্রস্তুত সহায়তার কথা",
    "cmd_caregiver-support_label": "যত্নদাতা হিসেবে আমার সহায়তা দরকার",
    "cmd_caregiver-support_desc": "সীমারেখা, নিজের যত্ন ও সহায়তা",
    "cmd_call-emergency_label": "জরুরি সহায়তায় কল করুন",
    "cmd_call-emergency_desc": "112 এবং যাচাইকৃত পরের পদক্ষেপ"
  },
  "te": {
    "heroLead": "మీకు ",
    "heroEmphasis": "ఇప్పుడే ",
    "heroTail": "ఏం కావాలి?",
    "modeIndividual": "నాకు సహాయం కావాలి",
    "modeCaregiver": "నేను ఒకరికి తోడుగా ఉన్నాను",
    "ctxKicker": "ఇప్పుడు",
    "ctxAlone": "నేను ఒంటరిగా ఉన్నాను",
    "ctxWithSomeone": "ఎవరితోనో ఉన్నాను",
    "setting_home": "ఇల్లు",
    "setting_outside": "బయట",
    "setting_work": "పని వద్ద",
    "setting_social": "ఇతరులతో",
    "setting_driving": "వాహనం నడుపుతూ",
    "speak": "మాట్లాడండి",
    "listening": "వింటున్నాను…",
    "liveVoice": "నేరుగా మాట్లాడండి",
    "inputPlaceholder": "…లేదా ఏమవుతోందో చెప్పండి / టైప్ చేయండి (ఐచ్ఛికం)",
    "send": "పంపండి",
    "emergencyHelp": "అత్యవసర సహాయం",
    "footerDisclaimer": "IBUKI Circle నిపుణుల, మనుషుల సంరక్షణకు తోడ్పాటు మాత్రమే — ఇది నిర్ధారణ, చికిత్స లేదా అత్యవసర సేవ కాదు. తక్షణ ప్రమాదంలో ఉంటే, కాల్ చేయండి",
    "footerPrivacy": "గోప్యత: మీరు నొక్కినది, చెప్పినది లేదా టైప్ చేసినది ఈ సమాధానం కోసం మాత్రమే వాడతాం — మా సర్వర్లలో ఎప్పుడూ నిల్వ చేయము, మీ చర్య లేకుండా ఎవరితోనూ పంచుకోము.",
    "cmd_urge_label": "నాకు బలమైన కోరిక వస్తోంది",
    "cmd_urge_desc": "దీన్ని దాటేందుకు వెంటనే ఒక ప్రణాళిక పొందండి",
    "cmd_panic_label": "నాకు భయంగా లేదా తట్టుకోలేనట్టుగా ఉంది",
    "cmd_panic_desc": "ప్రశాంతమైన చిన్న అడుగులతో మిమ్మల్ని నిలకడగా చేసుకోండి",
    "cmd_close-to-using_label": "వాడబోతున్న స్థితిలో ఉన్నాను",
    "cmd_close-to-using_desc": "ఇప్పుడే ఒక సురక్షితమైన తదుపరి అడుగు",
    "cmd_returned-to-use_label": "నేను మళ్లీ వాడాను",
    "cmd_returned-to-use_desc": "తీర్పు లేదు — స్థిరమైన తదుపరి అడుగులు",
    "cmd_need-someone_label": "నాకు ఇప్పుడు ఎవరైనా కావాలి",
    "cmd_need-someone_desc": "మీ వారికి పంపేందుకు సందేశం సిద్ధం చేయండి",
    "cmd_overdose-danger_label": "అధిక మోతాదు / ప్రమాదం ఉండవచ్చు",
    "cmd_overdose-danger_desc": "ధృవీకరించిన అత్యవసర సహాయం, వెంటనే",
    "cmd_possible-overdose_label": "అధిక మోతాదు ఉండవచ్చు",
    "cmd_possible-overdose_desc": "ధృవీకరించిన అత్యవసర చర్యలు, ఇప్పుడే",
    "cmd_they-are-distressed_label": "వారు కలవరంగా లేదా ఆందోళనగా ఉన్నారు",
    "cmd_they-are-distressed_desc": "ప్రశాంతపరిచే మాటలు",
    "cmd_start-conversation_label": "మాట్లాడటం మొదలుపెట్టేందుకు సహాయం చేయండి",
    "cmd_start-conversation_desc": "తోడ్పాటుగా, నిందించని మాటల నమూనా",
    "cmd_prepare-message_label": "తోడ్పాటు సందేశం సిద్ధం చేయండి",
    "cmd_prepare-message_desc": "వెంటనే పంపగల తోడ్పాటు మాటలు",
    "cmd_caregiver-support_label": "సంరక్షకుడిగా నాకు సహాయం కావాలి",
    "cmd_caregiver-support_desc": "హద్దులు, స్వీయ సంరక్షణ, అదనపు తోడ్పాటు",
    "cmd_call-emergency_label": "అత్యవసర సహాయానికి కాల్ చేయండి",
    "cmd_call-emergency_desc": "112 మరియు ధృవీకరించిన తదుపరి అడుగులు"
  },
  "mr": {
    "heroLead": "तुम्हाला ",
    "heroEmphasis": "आत्ता काय हवे आहे",
    "heroTail": "?",
    "modeIndividual": "मला मदत हवी आहे",
    "modeCaregiver": "मी कोणाला तरी मदत करत आहे",
    "ctxKicker": "आत्ता",
    "ctxAlone": "मी एकटा/एकटी आहे",
    "ctxWithSomeone": "कोणासोबत आहे",
    "setting_home": "घर",
    "setting_outside": "बाहेर",
    "setting_work": "कामावर",
    "setting_social": "लोकांसोबत",
    "setting_driving": "वाहन चालवत आहे",
    "speak": "बोला",
    "listening": "ऐकत आहे…",
    "liveVoice": "थेट आवाज",
    "inputPlaceholder": "…काय होत आहे ते बोला / लिहा (ऐच्छिक)",
    "send": "पाठवा",
    "emergencyHelp": "तातडीची मदत",
    "footerDisclaimer": "IBUKI Circle हे व्यावसायिक आणि मानवी काळजीला पूरक आहे — हे निदान, उपचार किंवा आपत्कालीन सेवा नाही. तातडीचा धोका असल्यास, कॉल करा",
    "footerPrivacy": "गोपनीयता: तुम्ही टॅप करता, बोलता किंवा लिहिता ते फक्त हा प्रतिसाद तयार करण्यासाठी वापरले जाते — आमच्या सर्व्हरवर कधीही साठवले जात नाही, आणि तुमच्या कृतीशिवाय शेअर केले जात नाही.",
    "cmd_urge_label": "मला वापरण्याची तीव्र ओढ येत आहे",
    "cmd_urge_desc": "ती ओढ कमी होईपर्यंत टिकून राहण्यासाठी लगेच योजना मिळवा",
    "cmd_panic_label": "मला घाबरल्यासारखे किंवा खूप भारावल्यासारखे वाटते",
    "cmd_panic_desc": "शांत, छोट्या पावलांनी स्वतःला स्थिर करा",
    "cmd_close-to-using_label": "मी वापरण्याच्या अगदी जवळ आहे",
    "cmd_close-to-using_desc": "आत्ता एक सुरक्षित पुढचे पाऊल",
    "cmd_returned-to-use_label": "मी पुन्हा वापर केला",
    "cmd_returned-to-use_desc": "कसलाही न्याय नाही — स्थिर पुढची पावले",
    "cmd_need-someone_label": "मला आत्ता कोणीतरी हवे आहे",
    "cmd_need-someone_desc": "तुमच्या जवळच्या लोकांसाठी संदेश तयार करा",
    "cmd_overdose-danger_label": "ओव्हरडोसची शक्यता / धोका",
    "cmd_overdose-danger_desc": "पडताळलेली तातडीची मदत, लगेच",
    "cmd_possible-overdose_label": "ओव्हरडोसची शक्यता",
    "cmd_possible-overdose_desc": "पडताळलेली तातडीची पावले, आत्ता",
    "cmd_they-are-distressed_label": "ती व्यक्ती अस्वस्थ किंवा चिडलेली आहे",
    "cmd_they-are-distressed_desc": "शांत करण्यासाठी सोपे शब्द",
    "cmd_start-conversation_label": "संवाद सुरू करण्यास मदत करा",
    "cmd_start-conversation_desc": "साथ देणारी, दोष न देणारी वाक्ये",
    "cmd_prepare-message_label": "आधार देणारा संदेश तयार करा",
    "cmd_prepare-message_desc": "लगेच पाठवता येतील असे आधाराचे शब्द",
    "cmd_caregiver-support_label": "काळजीवाहक म्हणून मला मदत हवी आहे",
    "cmd_caregiver-support_desc": "मर्यादा, स्वतःची काळजी आणि आधार",
    "cmd_call-emergency_label": "तातडीच्या मदतीसाठी कॉल करा",
    "cmd_call-emergency_desc": "112 आणि पडताळलेली पुढची पावले"
  },
  "kn": {
    "heroLead": "ನಿಮಗೆ ",
    "heroEmphasis": "ಈಗಲೇ",
    "heroTail": " ಏನು ಬೇಕು?",
    "modeIndividual": "ನನಗೆ ಬೆಂಬಲ ಬೇಕು",
    "modeCaregiver": "ನಾನು ಯಾರಿಗೋ ಬೆಂಬಲ ನೀಡುತ್ತಿದ್ದೇನೆ",
    "ctxKicker": "ಈಗ",
    "ctxAlone": "ನಾನು ಒಬ್ಬನೇ/ಒಬ್ಬಳೇ ಇದ್ದೇನೆ",
    "ctxWithSomeone": "ಯಾರೊಂದಿಗಾದರೂ ಇದ್ದೇನೆ",
    "setting_home": "ಮನೆ",
    "setting_outside": "ಹೊರಗೆ",
    "setting_work": "ಕೆಲಸದಲ್ಲಿ",
    "setting_social": "ಜನರ ಜೊತೆ",
    "setting_driving": "ಚಾಲನೆ ಮಾಡುತ್ತಿದ್ದೇನೆ",
    "speak": "ಮಾತನಾಡಿ",
    "listening": "ಕೇಳುತ್ತಿದ್ದೇನೆ…",
    "liveVoice": "ನೇರ ಧ್ವನಿ",
    "inputPlaceholder": "…ಅಥವಾ ಏನಾಗುತ್ತಿದೆ ಎಂದು ಹೇಳಿ / ಬರೆಯಿರಿ (ಐಚ್ಛಿಕ)",
    "send": "ಕಳುಹಿಸಿ",
    "emergencyHelp": "ತುರ್ತು ಸಹಾಯ",
    "footerDisclaimer": "IBUKI Circle ವೃತ್ತಿಪರ ಮತ್ತು ಮಾನವೀಯ ಆರೈಕೆಗೆ ಪೂರಕ — ಇದು ರೋಗನಿರ್ಣಯ, ಚಿಕಿತ್ಸೆ ಅಥವಾ ತುರ್ತು ಸೇವೆಯಲ್ಲ. ತಕ್ಷಣದ ಅಪಾಯದಲ್ಲಿ, ಕರೆ ಮಾಡಿ",
    "footerPrivacy": "ಗೌಪ್ಯತೆ: ನೀವು ಟ್ಯಾಪ್ ಮಾಡುವ, ಹೇಳುವ ಅಥವಾ ಬರೆಯುವ ಮಾಹಿತಿಯನ್ನು ಈ ಉತ್ತರ ರಚಿಸಲು ಮಾತ್ರ ಬಳಸಲಾಗುತ್ತದೆ — ನಮ್ಮ ಸರ್ವರ್‌ಗಳಲ್ಲಿ ಎಂದಿಗೂ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ, ನಿಮ್ಮ ಕ್ರಮವಿಲ್ಲದೆ ಹಂಚಿಕೊಳ್ಳುವುದಿಲ್ಲ.",
    "cmd_urge_label": "ನನಗೆ ತುಂಬಾ ಬಲವಾದ ಆಸೆ ಬರುತ್ತಿದೆ",
    "cmd_urge_desc": "ಅದನ್ನು ತಡೆಯಲು ತಕ್ಷಣದ ಯೋಜನೆ ಪಡೆಯಿರಿ",
    "cmd_panic_label": "ನನಗೆ ಗಾಬರಿ ಅಥವಾ ತುಂಬಾ ಒತ್ತಡವಾಗಿದೆ",
    "cmd_panic_desc": "ಶಾಂತವಾದ ಸಣ್ಣ ಹೆಜ್ಜೆಗಳಿಂದ ನಿಮ್ಮನ್ನು ಸ್ಥಿರಗೊಳಿಸಿ",
    "cmd_close-to-using_label": "ನಾನು ಬಳಸಲು ತುಂಬಾ ಹತ್ತಿರದಲ್ಲಿದ್ದೇನೆ",
    "cmd_close-to-using_desc": "ಈಗಲೇ ಒಂದು ಸುರಕ್ಷಿತ ಮುಂದಿನ ಹೆಜ್ಜೆ",
    "cmd_returned-to-use_label": "ನಾನು ಮತ್ತೆ ಬಳಸಿದ್ದೇನೆ",
    "cmd_returned-to-use_desc": "ತೀರ್ಪಿಲ್ಲದೆ — ಸ್ಥಿರವಾದ ಮುಂದಿನ ಹೆಜ್ಜೆಗಳು",
    "cmd_need-someone_label": "ನನಗೆ ಈಗ ಯಾರಾದರೂ ಬೇಕು",
    "cmd_need-someone_desc": "ನಿಮ್ಮ ಆಪ್ತರಿಗೆ ಸಂದೇಶ ಸಿದ್ಧಪಡಿಸಿ",
    "cmd_overdose-danger_label": "ಓವರ್‌ಡೋಸ್ / ಅಪಾಯ ಇರಬಹುದು",
    "cmd_overdose-danger_desc": "ಪರಿಶೀಲಿತ ತುರ್ತು ಸಹಾಯ, ತಕ್ಷಣವೇ",
    "cmd_possible-overdose_label": "ಓವರ್‌ಡೋಸ್ ಇರಬಹುದು",
    "cmd_possible-overdose_desc": "ಪರಿಶೀಲಿತ ತುರ್ತು ಕ್ರಮಗಳು, ಈಗ",
    "cmd_they-are-distressed_label": "ಅವರು ತುಂಬಾ ಕಳವಳಗೊಂಡಿದ್ದಾರೆ ಅಥವಾ ಉದ್ವಿಗ್ನರಾಗಿದ್ದಾರೆ",
    "cmd_they-are-distressed_desc": "ಶಾಂತಗೊಳಿಸಲು ಸರಳ ಮಾತುಗಳು",
    "cmd_start-conversation_label": "ಮಾತು ಆರಂಭಿಸಲು ಸಹಾಯ ಮಾಡಿ",
    "cmd_start-conversation_desc": "ಬೆಂಬಲದ, ದೋಷಾರೋಪವಿಲ್ಲದ ಮಾತಿನ ಮಾದರಿ",
    "cmd_prepare-message_label": "ಬೆಂಬಲದ ಸಂದೇಶ ಸಿದ್ಧಪಡಿಸಿ",
    "cmd_prepare-message_desc": "ಕಳುಹಿಸಲು ಸಿದ್ಧವಾದ ಬೆಂಬಲದ ಮಾತುಗಳು",
    "cmd_caregiver-support_label": "ಆರೈಕೆದಾರನಾಗಿ/ಆರೈಕೆದಾರಳಾಗಿ ನನಗೆ ಬೆಂಬಲ ಬೇಕು",
    "cmd_caregiver-support_desc": "ಮಿತಿಗಳು, ಸ್ವ-ಆರೈಕೆ ಮತ್ತು ನೆರವು",
    "cmd_call-emergency_label": "ತುರ್ತು ಸಹಾಯಕ್ಕೆ ಕರೆ ಮಾಡಿ",
    "cmd_call-emergency_desc": "112 ಮತ್ತು ಪರಿಶೀಲಿತ ಮುಂದಿನ ಹೆಜ್ಜೆಗಳು"
  },
  "ml": {
    "heroLead": "നിങ്ങൾക്ക് ",
    "heroEmphasis": "ഇപ്പോൾ തന്നെ ",
    "heroTail": "എന്താണ് വേണ്ടത്?",
    "modeIndividual": "എനിക്ക് പിന്തുണ വേണം",
    "modeCaregiver": "ഞാൻ ഒരാളെ പിന്തുണയ്ക്കുന്നു",
    "ctxKicker": "ഇപ്പോൾ",
    "ctxAlone": "ഞാൻ ഒറ്റയ്ക്കാണ്",
    "ctxWithSomeone": "ഒരാളോടൊപ്പം",
    "setting_home": "വീട്",
    "setting_outside": "പുറത്ത്",
    "setting_work": "ജോലിസ്ഥലം",
    "setting_social": "ആളുകൾക്കൊപ്പം",
    "setting_driving": "വാഹനം ഓടിക്കുമ്പോൾ",
    "speak": "സംസാരിക്കുക",
    "listening": "കേൾക്കുന്നു…",
    "liveVoice": "തത്സമയ ശബ്ദം",
    "inputPlaceholder": "…അല്ലെങ്കിൽ എന്താണ് സംഭവിക്കുന്നതെന്ന് പറയുക / ടൈപ്പ് ചെയ്യുക (നിർബന്ധമില്ല)",
    "send": "അയക്കുക",
    "emergencyHelp": "അടിയന്തര സഹായം",
    "footerDisclaimer": "IBUKI Circle പ്രൊഫഷണൽ, മാനുഷിക പരിചരണത്തിന് ഒരു കൂട്ടായ്മയാണ് — ഇത് രോഗനിർണയമോ ചികിത്സയോ അടിയന്തര സേവനമോ അല്ല. ഉടനടി അപകടമുണ്ടെങ്കിൽ വിളിക്കുക",
    "footerPrivacy": "സ്വകാര്യത: നിങ്ങൾ ടാപ്പ് ചെയ്യുന്നതും പറയുന്നതും ടൈപ്പ് ചെയ്യുന്നതും ഈ മറുപടി ഉണ്ടാക്കാൻ മാത്രം ഉപയോഗിക്കും — ഞങ്ങളുടെ സെർവറുകളിൽ സൂക്ഷിക്കില്ല, നിങ്ങളുടെ നടപടിയില്ലാതെ പങ്കിടില്ല.",
    "cmd_urge_label": "എനിക്ക് ശക്തമായ ഉപയോഗത്വര തോന്നുന്നു",
    "cmd_urge_desc": "ഇത് കടന്നുപോകാൻ ഉടൻ ഒരു പദ്ധതി നേടുക",
    "cmd_panic_label": "എനിക്ക് പരിഭ്രമമോ അമിതഭാരമോ തോന്നുന്നു",
    "cmd_panic_desc": "ശാന്തമായ ചെറിയ ഘട്ടങ്ങളിലൂടെ സ്വയം ഉറപ്പിക്കുക",
    "cmd_close-to-using_label": "ഞാൻ ഉപയോഗിക്കാൻ പോകുന്ന ഘട്ടത്തിലാണ്",
    "cmd_close-to-using_desc": "ഇപ്പോൾ ചെയ്യാവുന്ന ഒരു സുരക്ഷിത നടപടി",
    "cmd_returned-to-use_label": "ഞാൻ വീണ്ടും ഉപയോഗിച്ചു",
    "cmd_returned-to-use_desc": "വിധിയെഴുത്തില്ല — ഉറച്ച അടുത്ത ഘട്ടങ്ങൾ",
    "cmd_need-someone_label": "എനിക്ക് ഇപ്പോൾ ഒരാൾ വേണം",
    "cmd_need-someone_desc": "നിങ്ങളുടെ അടുത്തവർക്കായി ഒരു സന്ദേശം തയ്യാറാക്കുക",
    "cmd_overdose-danger_label": "അമിത അളവോ അപകടമോ ആകാം",
    "cmd_overdose-danger_desc": "പരിശോധിച്ച അടിയന്തര സഹായം, ഉടൻ",
    "cmd_possible-overdose_label": "അമിത അളവായിരിക്കാം",
    "cmd_possible-overdose_desc": "പരിശോധിച്ച അടിയന്തര ഘട്ടങ്ങൾ, ഇപ്പോൾ",
    "cmd_they-are-distressed_label": "അവർ അസ്വസ്ഥരോ പ്രകോപിതരോ ആണ്",
    "cmd_they-are-distressed_desc": "ശാന്തമാക്കാൻ സഹായിക്കുന്ന വാക്കുകൾ",
    "cmd_start-conversation_label": "ഒരു സംഭാഷണം തുടങ്ങാൻ സഹായിക്കൂ",
    "cmd_start-conversation_desc": "പിന്തുണയുള്ള, കുറ്റപ്പെടുത്താത്ത സംഭാഷണരീതി",
    "cmd_prepare-message_label": "പിന്തുണയുള്ള സന്ദേശം തയ്യാറാക്കൂ",
    "cmd_prepare-message_desc": "ഉടൻ അയക്കാവുന്ന പിന്തുണാ വാക്കുകൾ",
    "cmd_caregiver-support_label": "പരിചരിക്കുന്ന വ്യക്തിയായി എനിക്ക് പിന്തുണ വേണം",
    "cmd_caregiver-support_desc": "പരിധികൾ, സ്വയംപരിചരണം, സഹായം",
    "cmd_call-emergency_label": "അടിയന്തര സഹായം വിളിക്കുക",
    "cmd_call-emergency_desc": "112-ഉം പരിശോധിച്ച അടുത്ത ഘട്ടങ്ങളും"
  }
};

/** Returns the localized string, falling back to English. */
export function t(language: LanguageCode, key: UIKey): string {
  return UI_STRINGS[language]?.[key] ?? UI_STRINGS.en[key];
}
